<div class="main_content">
    <div class="adv_images">
        <img class="woman" src="<?php echo $this-> getViewFileUrl('img/picture_main.png'); ?>"/>
        <img class="man" src="<?php echo $this-> getViewFileUrl('img/picture_man.png'); ?>"/>
        <img class="flawour" src="<?php echo $this->getViewFileUrl('img/picture_flawour.png'); ?>"/>
        <img class="sale" src="<?php echo $this->getViewFileUrl('img/picture_sale.png');?>"/>
        <img class="lorry" src="<?php echo $this->getViewFileUrl('img/picture_lorry.png'); ?>"/>
    </div>
    <div class="labels">
        <p class="hot_sel">Hot Sellers</p>
        <p class="trend">Here is what's trending on Luma right now</p>
    </div>
</div>

