<div class="menu">
    <div class="menu__column1">
        <h2><?php echo __('COMPANY INFO')?></h2>
        <ul class="left">
            <li><a href="#"><?php echo __('About us')?></a></li>
            <li><a href="#"><?php echo __('Contact us')?></a></li>
            <li><a href="#"><?php echo __('Sell to CWS')?></a></li>
            <li><a href="#"><?php echo __('Terms & Conditions')?></a></li>
            <li><a href="#"><?php echo __('Authenticity Guarantee')?></a></li>
            <li><a href="#"><?php echo __('Privacy Policy')?></a></li>
        </ul>
    </div>
    <div class="menu__column2">
        <h2><?php echo __('HELP CENTER')?></h2>
        <ul class="centr">
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('Shipping Policy')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Payment Options')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('Order Information')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('International Shipping')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('Return Policy')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('Product Warranty')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('Repair Centr')?></a></li>
            <li><a href="#" title="<?php echo __('Contact Us')?>"><?php echo __('FAQ')?></a></li>
        </ul>
    </div>
    <div class="menu__column3">
        <h2><?php echo __('MY ACCOUNT')?></h2>
        <ul class="centr">
            <li><a href="#" title="<?php echo __('About Us')?>"><?php echo __('Manage Your Account')?></a></li>
            <li><a href="#" title="<?php echo __('Privacy Policy')?>"><?php echo __('Order Status')?></a></li>
        </ul>
        <div class="subscribe_icons">
        <h2><?php echo __('FOLLOW US')?></h2>
            <div class="circle_icon"><img src="<?php echo $this->getViewFileUrl('img/facebook_icon.png')?>"/></div>
            <div class="circle_icon"><img src="<?php echo $this->getViewFileUrl('img/google_icon.png')?>"/></div>
            <div class="circle_icon"><img src="<?php echo $this->getViewFileUrl('img/pinterest_icon.png')?>"/></div>
            <div class="circle_icon"><img src="<?php echo $this->getViewFileUrl('img/twitter_icon.png')?>"/></div>
        </div>
    </div>
    <div class="menu__column4">
        <h2 class="subsc"><?php echo __('STAY UP TO DATE ON DEALS & PROMOTIONS')?></h2>
        <form method="post">
            <input type="text" name="useremail" style="width: 299px;height: 29px; position: relative; top: 20px" placeholder="Email" ><br>
            <input type="submit" name="button_subscribe" class="sub_but" value="SUBSCRIBE">
        </form>

    </div>
</div>
